services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - .${POSTGRES_LOCAL_DATA_PATH}:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: 
      - .env
    ports:
      - 80:80
    volumes:
      - .${PGADMIN_SERVER_JSON_FILE}:/servers.json

  fastapi-project-template:
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile.local
    image: fastapi-project-template:latest
    container_name: fastapi-project-template
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres

  fastapi-project-template-debug:
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile.debug
    image: fastapi-project-template:debug
    container_name: fastapi-project-template-debug
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - 5678:5678
      - 8081:8080
    depends_on:
      - postgres
