services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - .${POSTGRES_LOCAL_DATA_PATH}:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - .${PGADMIN_SERVER_JSON_FILE}:/servers.json

  fastapi-crud-starter:
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile.local
    image: fastapi-crud-starter:latest
    container_name: fastapi-crud-starter
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres

  fastapi-crud-starter-debug:
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile.debug
    image: fastapi-crud-starter:debug
    container_name: fastapi-crud-starter-debug
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - 5678:5678
      - 8081:8080
    depends_on:
      - postgres
