"""delete status field

Revision ID: cc5eda956633
Revises: 7132989f72ee
Create Date: 2025-01-20 19:29:46.847418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc5eda956633"
down_revision: Union[str, None] = "7132989f72ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items",
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
